name: CI/CD Docker - Build & Push

on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authentification à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push backend
      - name: Build backend Docker image
        run: |
          docker build -t sasso17/bobapp-back:latest ./back
          docker push sasso17/bobapp-back:latest

      # Build & push frontend
      - name: Build frontend Docker image
        run: |
          docker build -t sasso17/bobapp-front:latest ./front
          docker push sasso17/bobapp-front:latest
